### ISSUE TITLE
TypeError: path must be a string

### ISSUE THREAD

**Issue by oliviertassinari** [zertosh/class-props-codemod#1]
I have noticed the following error while parsing the source code of `material-ui`:

```
Processing 1 files...
Spawning 1 workers with 1 files each...
fs.js:263
  binding.open(pathModule._makeLong(path),
          ^

TypeError: path must be a string
```

This is because of this first error: `Skipping path "src/**/**/**/*" which does not exist.`.
That's not really important. I just thought it would be great to let you know.

**Comment by zertosh** [comment]
Thanks! That seems like it's coming from [jscodeshift](https://github.com/facebook/jscodeshift). I tried to repro but couldn't.

<img width="499" alt="tvidm" src="https://cloud.githubusercontent.com/assets/830952/12700506/ff0f6114-c79a-11e5-8662-211cd0ef41a5.png">

**Comment by oliviertassinari** [comment]
Yes, I think that it's linked to jscodeshift. The path I provide (`src/**/**/**/*`) doesn't match any files.

**Comment by zertosh** [comment]
jscodeshift itself doesn't understand globs. so if you used `jscodeshift src/**/**/**/*` (which is a weird pattern) then it was your shell that expanded that.

I used this transform internally at facebook. To pass tens of thousands of files to any command (and exclude stuff you don't want), you need a bit of command-line foo. I use some variant of the command below. It will search for all js files in `~/fb` and exclude anything in a `node_modules` or `third_party` dir:

``` sh
find ~/fb \
    \( \
      -path '*/node_modules/*' -o \
      -path '*/third_party/*' \
    \) -prune -o -name '*.js' -print \
  | xargs jscodeshift --transform ~/src/github/class-props-codemod
```

**Comment by oliviertassinari** [comment]
> which is a weird pattern

I couldn't agree more. I don't event know why it's working in some cases :grin:.
Thanks for your help. This will help us to migrate to ES6 classes!
